# DEEP Learning with Tensorflow

#### Install required packages

In [1]:
%pip install --upgrade scikit-learn scipy

Note: you may need to restart the kernel to use updated packages.


## Explore the dataset

In [2]:
# Load the dataset
import pandas as pd

# load the training dataset (excluding rows with null values)
penguins = pd.read_csv('./../../data/penguins.csv').dropna()

print(penguins.size)

1710


In [3]:
penguins.head()

CulmenLength  CulmenDepth  FlipperLength  BodyMass  Species
0          39.1         18.7          181.0    3750.0        0
1          39.5         17.4          186.0    3800.0        0
2          40.3         18.0          195.0    3250.0        0
4          36.7         19.3          193.0    3450.0        0
5          39.3         20.6          190.0    3650.0        0

In [4]:
# Data Normalization
penguins['FlipperLength'] = penguins['FlipperLength'] / 10
penguins['BodyMass'] = penguins['BodyMass'] / 100

In [5]:
penguins.head()

CulmenLength  CulmenDepth  FlipperLength  BodyMass  Species
0          39.1         18.7           18.1      37.5        0
1          39.5         17.4           18.6      38.0        0
2          40.3         18.0           19.5      32.5        0
4          36.7         19.3           19.3      34.5        0
5          39.3         20.6           19.0      36.5        0

# Handle Dataset Size

Dataset is too small for useful deep learning. Increase dataset size with **oversamling**.

In [6]:
print(penguins.size)

# Oversampling
for i in range(3):
    penguins = pd.concat([penguins, penguins], ignore_index=True)

print(penguins.size)

1710
13680


In [7]:
# Display a random sample of 10 observations
sample = penguins.sample(10)
sample

CulmenLength  CulmenDepth  FlipperLength  BodyMass  Species
2068          42.5         20.7           19.7     45.00        0
659           45.5         17.0           19.6     35.00        2
1057          39.5         17.8           18.8     33.00        0
2709          46.2         17.5           18.7     36.50        2
2547          48.7         14.1           21.0     44.50        1
1001          45.5         17.0           19.6     35.00        2
816           37.5         18.5           19.9     44.75        0
191           42.7         13.7           20.8     39.50        1
2             40.3         18.0           19.5     32.50        0
1319          49.2         18.2           19.5     44.00        2

In [8]:
# Target - species value
penguins['Species'].unique()

array([0, 1, 2])

In [9]:
penguins['Species'].unique()

array([0, 1, 2])

In [10]:
penguin_classes = ['Adelie', 'Gentoo', 'Chinstrap']

print(sample.columns[0:5].values, 'SpeciesName')

for index, row in penguins.sample(10).iterrows():
    print('[',row[0], row[1], row[2],row[3], int(row[4]), ']',penguin_classes[int(row[-1])])

['CulmenLength' 'CulmenDepth' 'FlipperLength' 'BodyMass' 'Species'] SpeciesName
[ 48.4 14.4 20.3 46.25 1 ] Gentoo
[ 49.3 19.9 20.3 40.5 2 ] Chinstrap
[ 50.8 19.0 21.0 41.0 2 ] Chinstrap
[ 53.5 19.9 20.5 45.0 2 ] Chinstrap
[ 36.3 19.5 19.0 38.0 0 ] Adelie
[ 34.6 21.1 19.8 44.0 0 ] Adelie
[ 38.1 16.5 19.8 38.25 0 ] Adelie
[ 51.3 14.2 21.8 53.0 1 ] Gentoo
[ 40.3 18.5 19.6 43.5 0 ] Adelie
[ 46.9 16.6 19.2 27.0 2 ] Chinstrap


/tmp/ipykernel_9871/4059054900.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print('[',row[0], row[1], row[2],row[3], int(row[4]), ']',penguin_classes[int(row[-1])])


In [11]:
penguins['Species'].unique()

array([0, 1, 2])

## Split the dataset

In [12]:
from sklearn.model_selection import train_test_split

features = ['CulmenLength','CulmenDepth','FlipperLength','BodyMass']
label = 'Species'
   
# Split data 70%-30% into training set and test set
x_train, x_test, y_train, y_test = train_test_split(penguins[features].values,
                                                    penguins[label].values,
                                                    test_size=0.30,
                                                    random_state=0)

print ('Training Set: %d, Test Set: %d \n' % (len(x_train), len(x_test)))
print("Sample of features and labels:")

# Take a look at the first 25 training features and corresponding labels
for n in range(0,24):
    print(x_train[n], y_train[n], '(' + penguin_classes[y_train[n]] + ')')

Training Set: 1915, Test Set: 821 

Sample of features and labels:
[42.5 20.7 19.7 45. ] 0 (Adelie)
[45.6 20.3 19.1 46. ] 0 (Adelie)
[42.6 13.7 21.3 49.5] 1 (Gentoo)
[40.3 18.5 19.6 43.5] 0 (Adelie)
[39.7 17.7 19.3 32. ] 0 (Adelie)
[46.4 17.8 19.1 37. ] 2 (Chinstrap)
[38.8 20.  19.  39.5] 0 (Adelie)
[48.8 16.2 22.2 60. ] 1 (Gentoo)
[46.2 17.5 18.7 36.5] 2 (Chinstrap)
[59.6 17.  23.  60.5] 1 (Gentoo)
[41.5 18.5 20.1 40. ] 0 (Adelie)
[39.5 16.7 17.8 32.5] 0 (Adelie)
[50.5 15.9 22.5 54. ] 1 (Gentoo)
[45.6  19.4  19.4  35.25] 2 (Chinstrap)
[37.9  18.6  19.3  29.25] 0 (Adelie)
[51.1 16.3 22.  60. ] 1 (Gentoo)
[52.8 20.  20.5 45.5] 2 (Chinstrap)
[39.6 17.2 19.6 35.5] 0 (Adelie)
[51.1 16.3 22.  60. ] 1 (Gentoo)
[36.7 18.8 18.7 38. ] 0 (Adelie)
[49.1 15.  22.8 55. ] 1 (Gentoo)
[37.6 19.1 19.4 37.5] 0 (Adelie)
[36.  17.8 19.5 34.5] 0 (Adelie)
[39.1 18.7 18.1 37.5] 0 (Adelie)


## Install and import tensorflow

In [13]:
%pip install --no-cache-dir tensorflow

Note: you may need to restart the kernel to use updated packages.


In [14]:
# Import necessary libraries
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import models
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras import utils
from tensorflow.keras import optimizers

# Set random seed for reproducibility
tf.random.set_seed(0)

import importlib.metadata

print("Libraries imported.")

2025-05-31 10:56:49.562567: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-05-31 10:56:49.878640: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-05-31 10:56:50.076193: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1748667410.448152    9871 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1748667410.527020    9871 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1748667411.085825    9871 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linkin

Libraries imported.


In [15]:
# Check tesnsorflow && keras version
print('TensorFlow version:', tf.__version__)

try:
    keras_version = importlib.metadata.version("keras")
    print('Keras version:', keras_version)
except importlib.metadata.PackageNotFoundError:
    print("Keras is not installed separately, using TensorFlow's built-in Keras.")

TensorFlow version: 2.19.0
Keras version: 3.10.0


In [16]:
# Set data types for float features
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')

# Set data types for categorical labels
y_train = utils.to_categorical(y_train)
y_test = utils.to_categorical(y_test)
print('Ready...')

Ready...
